name: dev Actions
run-name: ${{ github.actor }} is running dev Actions on {{ $github.repository }} 

on: [push]
jobs:
  build: 
    runs-on: ununtu-latest
    steps: 
      - run: echo "Job now running on a ${{ runner.os }} server"
      - name: checkout branch
        uses: actions/checkout@v5
      - run: echo " The ${{ github.repository }} repository has been cloned to the runner."
      - name: List Files
      - run: |
          ls ${{ github.workspace }}