name: Python Build and Test
run-name: Building and Testing code on Github Repository ${{ github.repository }}

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  Core-Pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up latest python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip  # why do I need to cache pip

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python install -r requirements.txt
          pip install pytest

      - name: Run Pytest
        run: |
          pytest -v --maxfail=1 --junitxml=pytest-results.xml

      - name: Upload Pytest results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: report

  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: flake8 Lint
        uses: py-actions/flake8@v2
